# Generated by Django 5.0 on 2023-12-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputGenai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('bot_message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
    ]
