# Generated by Django 5.0 on 2023-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinputgenai_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
