# Generated by Django 5.0 on 2023-12-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinput_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
    ]
